CREATE DATABASE SENAI_SPMEDGROUP_TARDE

USE SENAI_SPMEDGROUP_TARDE

CREATE TABLE ESPECIALIDADES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE TIPO_DE_USUARIO(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE SITUACAO_DA_CONSULTA(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE CLINICA(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL
	,CNPJ VARCHAR(14) NOT NULL UNIQUE
	,RAZAO_SOCIAL VARCHAR(255) NOT NULL
	,ENDEREÇO VARCHAR(255) NOT NULL
);

CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY
	,EMAIL VARCHAR(255) NOT NULL UNIQUE
	,SENHA VARCHAR(255) NOT NULL
	,ID_TIPO INT NOT NULL FOREIGN KEY REFERENCES TIPO_DE_USUARIO(ID)
);

SELECT * FROM TIPO_DE_USUARIO
INSERT INTO TIPO_DE_USUARIO VALUES ('ADMINITRADOR');
SELECT * FROM USUARIOS;
INSERT INTO USUARIOS VALUES ('A@A.A', '123', 1)
,('A@A.B', '123', 1)
,('A@A.C', '123', 1)
,('A@A.D', '123', 1)
,('A@A.E', '123', 1)
,('A@A.F', '123', 1)
,('A@A.G', '123', 1)
,('A@A.H', '123', 1)
,('A@A.I', '123', 1)

CREATE TABLE PRONTUARIO(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL
	,ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
	,DATA_NASCIMENTO DATE NOT NULL
	,TELEFONE VARCHAR(11) NOT NULL
	,RG VARCHAR(9) NOT NULL UNIQUE
	,CPF VARCHAR(11) NOT NULL UNIQUE
	,ENDERECO VARCHAR(255) NOT NULL
);

CREATE TABLE MEDICOS(
	ID INT IDENTITY PRIMARY KEY
	,CRM BIGINT NOT NULL UNIQUE
	,NOME VARCHAR(255) NOT NULL
	,ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
	,ID_ESPECIALIDADE INT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES(ID)
	,ID_CLINICA INT NOT NULL FOREIGN KEY REFERENCES CLINICA(ID)
);

CREATE TABLE CONSULTAS(
	ID INT IDENTITY PRIMARY KEY
	,ID_PRONTUARIO INT NOT NULL FOREIGN KEY REFERENCES PRONTUARIO(ID)
	,ID_MEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICOS(ID)
	,DATA_CONSULTA DATETIME NOT NULL
	,ID_SITUACAO INT NOT NULL FOREIGN KEY REFERENCES SITUACAO_DA_CONSULTA(ID)
	,OBSERVACOES VARCHAR(255) NOT NULL
);

alter table prontuario
	alter column telefone varchar(50) not null

alter table consultas alter column observacoes varchar(255)